### ISSUE TITLE
Dans les render, mettre un tableau de tableau dans $_SESSION plutot que plusieurs variable

### ISSUE THREAD

**Issue by HoustonLFB** [GatherlySTRI/Gatherly#52]
l'idée vient de me venir en faisant l'annale de php

**Comment by Thomas97460** [comment]
Un tableau de quoi ?

**Comment by HoustonLFB** [comment]
> Un tableau de quoi ?

pour l'instant ya la majorité des render, ya les $_SESSION['id_utilisateur']), 'is_admin' => $_SESSION['est_Admin']. Tout faire dans une seul var _sessions pour uniformiser les render et pas avoir besoin de tout changer si on veut rajouter une var dans les render

**Comment by Thomas97460** [comment]
ça serait beau. Sinon autant passer directement la variable SESSION au render

**Comment by HoustonLFB** [comment]
> ça serait beau. Sinon autant passer directement la variable SESSION au render

oui je viens d'y penser ce sera plus simple à faire

**Comment by HoustonLFB** [comment]
att ça marche là

**Comment by HoustonLFB** [comment]
J'ai testé sur toutes les pages
